server:
  port: 8081

spring:
  application:
    name: ticketwave-events
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ticketwave-sa}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms
      repositories:
        enabled: false
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

ticketwave:
  jwt:
    secret: ${JWT_SECRET:ChangeThisSecretKeyInProductionToASecureRandomValueOfAtLeast32BytesLong}
    expiration-ms: ${JWT_EXPIRATION:86400000}
  redis-prefix: ticketwave
  order-ttl-minutes: ${ORDER_TTL_MINUTES:15}
  bus:
    event-queue: ${TICKETWAVE_EVENT_QUEUE:ticketwave.events.all.api}
    command-queue: ${TICKETWAVE_COMMAND_QUEUE:ticketwave.commands.all.api}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.ticketwave: DEBUG